### ISSUE TITLE
Ô amigão?!, ta tudo errado  

### ISSUE THREAD

**Issue by zTrolly** [GiroFC/Sites-Diw#1]
![image6-1](https://user-images.githubusercontent.com/61760048/136264672-313ea03f-f420-45d3-ab5e-fa7a3e8c2aff.png)
@GiroFC

**Comment by GiroFC** [comment]
Teu cu

Em qua., 6 de out. de 2021 3:49 PM, Breno Lopes do Carmo <
***@***.***> escreveu:
